-- รันไฟล์นี้ใน Supabase > SQL Editor เพียงครั้งเดียว
create table if not exists public.shops (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category text not null default 'อื่น ๆ',
  address text not null default 'ตลาดกระทุ่มแบน',
  phone text,
  facebook text,
  line text,
  tiktok text,
  website text,
  image text,
  latitude double precision,
  longitude double precision,
  open_time time,
  close_time time,
  owner_note text,
  approved boolean not null default false,
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.shops add column if not exists open_time time;
alter table public.shops add column if not exists close_time time;
alter table public.shops add column if not exists owner_note text;
alter table public.shops enable row level security;

drop policy if exists "Anyone can view approved shops" on public.shops;
create policy "Anyone can view approved shops" on public.shops
for select to anon, authenticated using (approved = true);

drop policy if exists "Anyone can submit unapproved shops" on public.shops;
create policy "Anyone can submit unapproved shops" on public.shops
for insert to anon, authenticated
with check (approved = false and featured = false);

insert into public.shops(name,description,category,address,phone,facebook,line,tiktok,latitude,longitude,open_time,close_time,approved,featured)
select 'Snowtee ตลาดกระทุ่มแบน','เครื่องดื่ม ไอศกรีมซอฟต์เสิร์ฟ และเบเกอรี่ บรรยากาศริมคลอง','เครื่องดื่ม','ตลาดกระทุ่มแบน จังหวัดสมุทรสาคร','0642211876','https://facebook.com/snowtee68','snowtee68','https://www.tiktok.com/@snowtee68',13.6549,100.2639,'09:00','21:00',true,true
where not exists(select 1 from public.shops where name='Snowtee ตลาดกระทุ่มแบน');
